version: '3.8'

services:


  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.4
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker --log.level=DEBUG --api.dashboard=true
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock

  task:
    image: schedule-distributed-task:0.0.1-SNAPSHOT
#    ports:
#      - 8080:8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app-8000.rule=Host(`http://webservice.docker.localhost/`) && PathPrefix(`/puerto-8000`)"
      - "traefik.http.routers.app-8000.entrypoints=web"
      - "traefik.http.routers.app-8001.rule=Host(`http://webservice.docker.localhost/`) && PathPrefix(`/puerto-8001`)"
      - "traefik.http.routers.app-8001.entrypoints=web"

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres-init/:/docker-entrypoint-initdb.d/